#!/bin/bash

edit_flag=false

while getopts 'e' flag; do
  case "$flag" in
    e) edit_flag='true' ;;
  esac
done

if [ $edit_flag = true ]
then 
   vim "$HOME/dotfiles/manben/$2.ben"
else
   less "$HOME/dotfiles/manben/$1.ben"
fi
